# Generated by Django 5.1.2 on 2024-10-16 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_plans", "0002_personalbest_set_workoutplan_delete_trainingplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                ("date_completed", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="training_plans.set",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PersonalBest",
        ),
    ]
