# Generated by Django 5.1.2 on 2024-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_plans", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_trainer",
            field=models.BooleanField(default=False),
        ),
    ]
